SELECT * FROM chicago_crimes;

SET AUTOTRACE ON
SELECT * FROM chicago_crimes;

EXPLAIN PLAN FOR
SELECT * FROM chicago_crimes;
SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

-- start
-- 再多條件，COST相同
-- COST 390
SELECT *
FROM CHICAGO_CRIMES
WHERE ARREST='False';

-- COST 390
SELECT *
FROM CHICAGO_CRIMES
WHERE DATETIME > '10/08/2008' AND DATETIME < '10/12/2008';

-- COST 390
SELECT COUNT(*)
FROM CHICAGO_CRIMES
WHERE ARREST='True';


-- 建立index
CREATE INDEX ARR_IDX ON CHICAGO_CRIMES(ARREST);
CREATE INDEX DATE_IDX ON CHICAGO_CRIMES(DATETIME ASC);


-- 有加速
SELECT *
FROM CHICAGO_CRIMES
WHERE DATETIME > '10/08/2008' AND DATETIME < '10/12/2008';


-- 有加速
SELECT COUNT(*)
FROM CHICAGO_CRIMES
WHERE ARREST='True';


-- COST 390
SELECT *
FROM CHICAGO_CRIMES
WHERE ARREST='True';


-- FORCE TO USE THE INDEX
SELECT /*+ index(CHICAGO_CRIMES (ARREST)) */*
FROM CHICAGO_CRIMES
WHERE ARREST='True';



-- COST 390
SELECT COUNT(*)
FROM CHICAGO_CRIMES
WHERE LOCATION_DESCRIPTION='STREET';

CREATE INDEX LOC_IDX ON CHICAGO_CRIMES(LOCATION_DESCRIPTION);

-- 有加速
SELECT COUNT(*)
FROM CHICAGO_CRIMES
WHERE LOCATION_DESCRIPTION='STREET';

-- 
SELECT *
FROM CHICAGO_CRIMES
WHERE DATETIME > '10/08/2008' AND DATETIME < '10/12/2008' AND LOCATION_DESCRIPTION='STREET';


DROP INDEX DATE_IDX;
DROP INDEX ARR_IDX;
DROP INDEX LOC_IDX;


